# Generated by Django 4.2.7 on 2024-03-20 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phn_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phn_no', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('sal', models.CharField(max_length=20)),
                ('phn_no', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField(unique=True)),
                ('mname', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Protein Power and Drinks', 'Protein Power and Drinks'), ('Personal Care', 'Personal Care'), ('Baby Care', 'Baby Care')], max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('med_mfg', models.DateField()),
                ('med_exp', models.DateField()),
                ('med_mrp', models.IntegerField()),
                ('med_stock', models.IntegerField()),
                ('med_perpack_price', models.IntegerField(editable=False)),
                ('med_remaining_stock', models.IntegerField()),
                ('med_costprice', models.IntegerField()),
                ('med_img', models.ImageField(upload_to='static/pic')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phn_no', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1001)),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Med_Payment',
            fields=[
                ('uniqueid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('delivery_information', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='medshop.user_delivery_information')),
                ('ordered_items', models.ManyToManyField(to='pharma.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('invoice_json', models.TextField()),
                ('inventory_reflected', models.BooleanField(default=True)),
                ('books_reflected', models.BooleanField(default=True)),
                ('invoice_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
