# Generated by Django 4.2.7 on 2024-03-20 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Med_Payment',
            new_name='Payment',
        ),
    ]
