# Generated by Django 4.2.7 on 2024-03-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_rename_med_payment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_customer',
            field=models.CharField(max_length=1000),
        ),
    ]
