# Generated by Django 4.2.7 on 2024-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_alter_invoice_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharm_ID', models.CharField(max_length=1000)),
                ('Pharm_Password', models.CharField(max_length=1000)),
            ],
        ),
    ]
