# Generated by Django 4.2.7 on 2024-04-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_pharmlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dirofuse',
            field=models.CharField(default='as directed by the physician', max_length=100000),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.CharField(default='sodium,potassium,e.t.c', max_length=100000),
        ),
        migrations.AddField(
            model_name='medicine',
            name='keybenefits',
            field=models.CharField(default='essential for health', max_length=100000),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='desc',
            field=models.CharField(max_length=100000),
        ),
    ]
