# Generated by Django 4.2.7 on 2024-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_medicine_dirofuse_medicine_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
