# Generated by Django 4.2.7 on 2024-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0006_medicine_prescription_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
