# Generated by Django 4.2.7 on 2024-04-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0007_alter_invoice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanitity_sold', models.PositiveIntegerField()),
                ('sales', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma.medicine')),
            ],
        ),
    ]
