# Generated by Django 4.2.7 on 2024-04-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0008_medicinesale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinesale',
            old_name='quanitity_sold',
            new_name='quantity_sold',
        ),
    ]
