# Generated by Django 4.2.7 on 2024-04-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0009_rename_quanitity_sold_medicinesale_quantity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinesale',
            old_name='sales',
            new_name='sale_date',
        ),
    ]
