# Generated by Django 4.2.7 on 2024-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0010_rename_sales_medicinesale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesale',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
