# Generated by Django 4.2.7 on 2024-04-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0011_alter_medicinesale_sale_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
