# Generated by Django 4.2.7 on 2024-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_delivery_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_email', models.EmailField(max_length=50)),
                ('delivery_phno', models.IntegerField(default=0)),
                ('delivery_address1', models.CharField(max_length=250)),
                ('delivery_address2', models.CharField(max_length=250, null=True)),
                ('delivery_city', models.CharField(max_length=50)),
                ('delivery_state', models.CharField(max_length=50)),
                ('delivery_zip', models.IntegerField()),
            ],
        ),
    ]
