# Generated by Django 4.2.7 on 2024-04-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_delivery_information',
            name='delivery_address2',
        ),
    ]
