# Generated by Django 4.2.7 on 2024-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medshop', '0002_remove_user_delivery_information_delivery_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_delivery_information',
            name='Prescription',
            field=models.ImageField(default='/static/media/pres_def.jpg', upload_to='static/prescriptions'),
        ),
    ]
