# Generated by Django 4.2.7 on 2024-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medshop', '0003_user_delivery_information_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_delivery_information',
            name='Prescription',
            field=models.ImageField(blank=True, default='/static/media/pres_def.jpg', null=True, upload_to='static/prescriptions'),
        ),
    ]
